LinearEGreedy:
  SimpleAgent:
    action_selection_policy:
      ASPEGreedy:
        epsilon: 0.1
    value_function:
      LinearEGreedy:
        item_var: 0.01
        iterations: 20
        num_lat: 20
        stop_criteria: 0.0009
        user_var: 0.01
        var: 0.05

ContextualEgreedy_Te0:
  SimpleAgent:
    action_selection_policy:
      ASPMismatchEgreedy:
        epsilon: 0.1
        k: 0
    value_function:
      ContextualEgreedy:
        item_var: 0.01
        iterations: 20
        num_lat: 20
        stop_criteria: 0.0009
        user_var: 0.01
        var: 0.05

ContextualEgreedy_Tge0:
  SimpleAgent:
    action_selection_policy:
      ASPMismatchEgreedy:
        epsilon: 0.1
        k: 5
    value_function:
      ContextualEgreedy:
        item_var: 0.01
        iterations: 20
        num_lat: 20
        stop_criteria: 0.0009
        user_var: 0.01
        var: 0.05

PTS:
  SimpleAgent:
    action_selection_policy:
      ASPGreedy: {}
    value_function:
      PTS:
        num_lat: 20
        num_particles: 5
        var: 0.05
        var_u: 0.01
        var_v: 0.3

ContextualPTS_Te0:
  SimpleAgent:
    action_selection_policy:
      ASPMismatchGreedy:
        k: 0
    value_function:
      ContextualPTS:
        num_lat: 20
        num_particles: 5
        var: 0.05
        var_u: 0.01
        var_v: 0.3

ContextualPTS_Tge0:
  SimpleAgent:
    action_selection_policy:
      ASPMismatchGreedy:
        k: 5
    value_function:
      ContextualPTS:
        num_lat: 20
        num_particles: 5
        var: 0.05
        var_u: 0.01
        var_v: 0.3

LinUCB:
  SimpleAgent:
    action_selection_policy:
      ASPGreedy: {}
    value_function:
      LinUCB:
        alpha: 0.5
        num_lat: 10

ContextualLinUCB_Te0:
  SimpleAgent:
    action_selection_policy:
      ASPMismatchGreedy:
        k: 0
    value_function:
      ContextualLinUCB:
        alpha: 0.3
        num_lat: 10

ContextualLinUCB_Tge0:
  SimpleAgent:
    action_selection_policy:
      ASPMismatchGreedy:
        k: 20
    value_function:
      ContextualLinUCB:
        alpha: 0.3
        num_lat: 10




Random:
  SimpleAgent:
    action_selection_policy:
      ASPGreedy: {}
    value_function:
      Random: {}

MostPopular:
  SimpleAgent:
    action_selection_policy:
      ASPGreedy: {}
    value_function:
      MostPopular: {}

UCB:
  SimpleAgent:
    action_selection_policy:
      ASPGreedy: {}
    value_function:
      UCB:
        c: 0.01

ThompsonSampling:
  SimpleAgent:
    action_selection_policy:
      ASPGreedy: {}
    value_function:
      ThompsonSampling:
        alpha_0: 1
        beta_0: 100

GLM_UCB:
  SimpleAgent:
    action_selection_policy:
      ASPGreedy: {}
    value_function:
      GLM_UCB:
        c: 4
        item_var: 0.01
        iterations: 20
        num_lat: 10
        stop_criteria: 0.0009
        user_var: 0.01
        var: 0.05

NICF:
  SimpleAgent:
    action_selection_policy:
      ASPGreedy: {}
    value_function:
      NICF:
        batch: 256
        clip_param: 0.2
        dropout_rate: 0.01
        gamma: 0.0
        inner_epoch: 50
        latent_factor: 10
        learning_rate: 0.001
        num_blocks: 1
        num_heads: 2
        restore_model: false
        rnn_layer: 2
        time_step: 100
        training_epoch: 4000

ICTRTS:
  SimpleAgent:
    action_selection_policy:
      ASPGreedy: {}
    value_function:
      ICTRTS:
        num_lat: 2
        num_particles: 5

ClusterBandit:
  SimpleAgent:
    action_selection_policy:
      ASPGreedy: {}
    value_function:
      ClusterBandit:
        B: 5
        C: 0.5
        D: 3
        num_clusters: 8
        num_lat: 10

LinearEGreedy:
  SimpleAgent:
    action_selection_policy:
      ASPEGreedy:
        epsilon: 0.1
    value_function:
      LinearEGreedy:
        var: 0.05
        item_var: 0.01
        user_var: 0.01
        iterations: 20
        num_lat: 10
        stop_criteria: 0.0009

AL_LinearEGreedy_Te0:
  SimpleAgent:
    action_selection_policy:
      ASPEGreedy:
        epsilon: 0.001
    value_function:
      LinearEGreedyLogPopEnt:
        var: 0.05
        user_var: 0.01
        item_var: 0.01
        iterations: 20
        num_lat: 15
        stop_criteria: 0.0009

AL_LinearEGreedy_Tge0:
  SimpleAgent:
    action_selection_policy:
      ASP_AL_EGreedy_PVE:
        epsilon: 0.0001
        k: 5
    value_function:
      LinearEGreedyLogPopEnt:
        var: 0.05
        user_var: 0.01
        item_var: 0.01
        iterations: 20
        num_lat: 15
        stop_criteria: 0.0009

PTS:
  SimpleAgent:
    action_selection_policy:
      ASPGreedy: {}
    value_function:
      PTS:
        num_lat: 10
        num_particles: 5
        var: 0.01
        var_u: 0.173
        var_v: 2.65

AL_PTS_Te0:
  SimpleAgent:
    action_selection_policy:
      ASPGreedy: {}
    value_function:
      PTSLogPopEnt:
        num_lat: 20
        num_particles: 5
        var: 0.5
        var_u: 1.0
        var_v: 1.0

AL_PTS_Tge0:
  SimpleAgent:
    action_selection_policy:
      ASP_AL_EGreedy_PVE:
        epsilon: 0.0001
        k: 5
    value_function:
      PTSLogPopEnt:
        num_lat: 20
        num_particles: 5
        var: 0.5
        var_u: 1.0
        var_v: 1.0

LinearUCB:
  SimpleAgent:
    action_selection_policy:
      ASPGreedy: {}
    value_function:
      LinearUCB:
        alpha: 1.0
        var: 0.05
        user_var: 0.01
        item_var: 0.01
        iterations: 20
        num_lat: 10
        stop_criteria: 0.0009

AL_LinearUCB_Te0:
  SimpleAgent:
    action_selection_policy:
      ASPGreedy: {}
    value_function:
      LinearUCBLogPopEnt:
        alpha: 1.0
        var: 0.05
        user_var: 0.01
        item_var: 0.01
        iterations: 20
        num_lat: 20
        stop_criteria: 0.0009

AL_LinearUCB_Tge0:
  SimpleAgent:
    action_selection_policy:
      ASP_AL_EGreedy_PVE:
        epsilon: 0.0001
        k: 5
    value_function:
      LinearUCBLogPopEnt:
        alpha: 1.0
        var: 0.05
        user_var: 0.01
        item_var: 0.01
        iterations: 20
        num_lat: 20
        stop_criteria: 0.0009

LinUCB:
  SimpleAgent:
    action_selection_policy:
      ASPGreedy: {}
    value_function:
      LinUCB:
        alpha: 0.9
        num_lat: 5

AL_LinUCB_Te0:
  SimpleAgent:
    action_selection_policy:
      ASPGreedy: {}
    value_function:
      WSCB:
        alpha: 1
        num_lat: 10

AL_LinUCB_Tge0:
  SimpleAgent:
    action_selection_policy:
      ASP_AL_EGreedy_PVE:
        epsilon: 0.0001
        k: 20
    value_function:
      WSCB:
        alpha: 1
        num_lat: 10
