Random:
  name: Random

MostPopular:
  name: Popular

UCB:
  name: UCB

ThompsonSampling:
  name: TS

LinearEGreedy:
  name: e-Greedy

EGreedy:
  name: e-Greedy

LinearUCB:
  name: LinearUCB

GLM_UCB:
  name: GLM-UCB

NICF:
  name: NICF

PTS:
  name: PTS

ICTRTS:
  name: ICTRTS

ClusterBandit:
  name: Cluster Bandit

LinearEGreedy:
  name: LinearEGreedy

ContextualEgreedy_Te0:
  name: LinearEGreedy$_{t=0}$

ContextualEgreedy_Tge0:
  name: LinearEGreedy$_{t>=0}$

PTS:
  name: PTS

ContextualPTS_Te0:
  name: PTS$_{t=0}$

ContextualPTS_Tge0:
  name: PTS$_{t>=0}$

LinUCB:
  name: LinUCB

ContextualLinUCB_Te0:
  name: LinUCB$_{t=0}$

ContextualLinUCB_Tge0:
  name: LinUCB$_{t>=0}$
